FROM archlinux:latest as builder

RUN pacman -Sy --noconfirm
RUN pacman -S --noconfirm base-devel gcc bazel

COPY /src /usr/src/hypercache

WORKDIR /usr/src/hypercache

RUN bazel build //hypercache_db

FROM alpine:latest
COPY --from=builder /usr/src/hypercache/bazel-bin/hypercache_db/hypercache_db /usr/bin/hc_db

RUN apk add libstdc++

ENTRYPOINT ["/usr/bin/hc_db"]
